// <auto-generated />
namespace VehiclesManager.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Removedpluralinvehiceregistration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Removedpluralinvehiceregistration));
        
        string IMigrationMetadata.Id
        {
            get { return "202309262343241_Removed plural in vehice registration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
