// <auto-generated />
namespace VehiclesManager.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Addedcellphomenumberandemailondriverdetails : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addedcellphomenumberandemailondriverdetails));
        
        string IMigrationMetadata.Id
        {
            get { return "202309270042540_Added cellphome number and email on driver details"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
